### ISSUE TITLE
如何处理初始化校准与关节坐标系不一致问题？

### ISSUE THREAD

**Issue by BestPolarBear** [isNineSun/Human-Pose-Estimation---Motion-Capture-Device#3]
请问您一下，你是如何处理初始化校准、传感器佩戴便宜、人物模型关节坐标系不一致等问题，期待您的回复，Thanks!

**Comment by isNineSun** [comment]
不好意思，我不常看github，一直没看到你的回复。
首先需要声明是，这是个做来玩玩的项目，可能对你的问题并没有一个很完善的解决方案，很多东西比较将就，你可以参考更成熟的项目比如slimVR项目。

**初始化校准的问题**：在佩戴前需要设备尽可能水平放置，校准后才进行佩戴，很久之前写的代码记忆有点模糊，我记得代码中会取1000组（大概）数据去计算offset。
**佩戴偏移问题**：这个我完全没做软件的解决方案，就我所知，索尼之前推出的那个成品的动捕设备，也是需要佩戴规范的。
**任务关节坐标系问题**：这个我在另一个上位机的项目里面有提到，我模型里面用的是传统的正向运动学，在Unity里面任务的关节作为上一个关节的子节点，人物在T-Pose的状态下，每个子物体的初始坐标就是0，我只需要将三个角度以合适的方式赋值给他们就可以了，但这就要求人体捕捉的设备跟对应关节是一一绑定的，因为每个关节对roll pitch和yaw的处理方案都不相同，这里的处理主要在上位机的部分。同样对应参考别的成品动捕方案，在开始之前也是需要人物和模型做一个或者几个姿势的Check的。
